name: Update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
      - name: Build
        run: go build -v .
      - name: Scrape
        env:
          # We split requests across a couple of different GitHub Apps
          GH_APP_ID_1: ${{ vars.GH_APP_ID_1 }}
          GH_APP_ID_2: ${{ vars.GH_APP_ID_2 }}
          GH_APP_ID_3: ${{ vars.GH_APP_ID_3 }}
          GH_APP_INSTALLATION_ID_1: ${{ vars.GH_APP_INSTALLATION_ID_1 }}
          GH_APP_INSTALLATION_ID_2: ${{ vars.GH_APP_INSTALLATION_ID_2 }}
          GH_APP_INSTALLATION_ID_3: ${{ vars.GH_APP_INSTALLATION_ID_3 }}
          GH_APP_PRIVATE_KEY_1: ${{ secrets.GH_APP_PRIVATE_KEY_1 }}
          GH_APP_PRIVATE_KEY_2: ${{ secrets.GH_APP_PRIVATE_KEY_2 }}
          GH_APP_PRIVATE_KEY_3: ${{ secrets.GH_APP_PRIVATE_KEY_3 }}
        run: |
          seq 2007 $(date '+%Y') | parallel --line-buffer --jobs=3 'GH_APP_ID=$GH_APP_ID_{%} GH_APP_INSTALLATION_ID=$GH_APP_INSTALLATION_ID_{%} GH_APP_PRIVATE_KEY=$GH_APP_PRIVATE_KEY_{%} ./github-top-repos "stars:>=100 created:{}-01-01T00:00:00Z..{}-12-31T23:59:59Z" > {}.csv'
      - name: Merge
        run: |
          echo "name,stars,created_at,pushed_at" > top.csv
          sort --field-separator=, --numeric-sort --reverse --key=2 20*.csv >> top.csv
          head -n101 top.csv > top-100.csv
          head -n1001 top.csv > top-1000.csv
          head -n10001 top.csv > top-10000.csv
          head -n1000001 top.csv > top-100000.csv
      - name: Commit
        run: |
          git config --global user.name "Luke Young"
          git config --global user.email "541842+bored-engineer@users.noreply.github.com"
          git add top*.csv
          git commit -m "Update: $(date)"
          git push
